### ISSUE TITLE
max key size 56?

### ISSUE THREAD

**Issue by codeorganic** [jashandeep-sohi/python-blowfish#12]
Why is the max key size 56?

**Comment by jashandeep-sohi** [comment]
Because that's what the spec say: "between 32 and 448 **bits**". So, that's between 4 and 56 bytes.

Now, if you are asking a deeper question of why cryptographically it is limited to 56 bytes, you might find the answer in the Blowfish paper at <https://www.schneier.com/paper-blowfish-fse.html>

**Comment by codeorganic** [comment]
Perfect!  Thanks for that URL it makes a lot of sense.  The 56 threw me off guard because many of the other libraries outside of python do not have this requirement in place.
