### ISSUE TITLE
Bytes to str and back, ctr_counter

### ISSUE THREAD

**Issue by shakna-israel** [jashandeep-sohi/python-blowfish#17]
Hoping you might be able to point me in the right direction.

I'm using ```encrypt_ctr``` successfully, however the storage medium I'm using requires me to store into str. I'm not sure what encoding/decoding to use to make it go to a str, and then be able to be converted from str back to bytes for ```decrypt_ctr``` to handle.

At the moment, decryption is sort of like:

```
encryptedBytes = b"".join(encryptedBytesList)
with open(metadata["filename"], "wb") as openFile:
            decoded_data = b"".join(self.cipher.decrypt_ctr(data, self.encrypt_counter))
            openFile.write(decoded_data)
```

And encryption, sort of like:

```
with open(os.path.expanduser("~/reddiSync/") + filename, "rb") as openFile:
            data = openFile.read()
            encoded_data = b"".join(self.cipher.encrypt_ctr(data, self.encrypt_counter))
        encoded_list = [encoded_data[i:i+1000] for i in range(0, len(data), 1000)]
        return [str(x) for x in encoded_list]
```

Its ensuring the original conversion to str that's the issue.

UTF-8 isn't compatible with some of the bytes produced, so is there an encoding I could use?

**Comment by jashandeep-sohi** [comment]
I believe `latin-1` might be what you are looking for.
```
>>> str(bytes(range(0, 256), "latin-1")
...
```
There might be other encoding that could work also. Look for something that has exactly 256 character possibilities.

BTW, there is also [`uu`](https://docs.python.org/3.5/library/uu.html#module-uu) if you want `ascii` only chars. Might add some overhead though.

**Comment by jashandeep-sohi** [comment]
Closing, no response.
