### ISSUE TITLE
Bad Pi!

### ISSUE THREAD

**Issue by Moneetor** [jashandeep-sohi/python-blowfish#18]
After using 'PI' sign in source, i can't install module via pip on Kubuntu/Pythin3.5, and QPython/Python3.5. When i remove 'PI' sign,  importing of module works well.
`
>>> import blowfish
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "blowfish.py", line 32
SyntaxError: Non-ASCII character '\xcf' in file blowfish.py on line 32, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
>>> 
`

**Comment by jashandeep-sohi** [comment]
That's strange. I was under the impression that UTF-8 is the default encoding for source code in Python 3: https://docs.python.org/3/howto/unicode.html#the-string-type, https://www.python.org/dev/peps/pep-3120/

**Comment by Moneetor** [comment]
I see, you can;'t believe UTF, is not default on some platforms. Believe it! On some platforms you meet latin1 or latin2 or even cp125x. Nobody with this conflagration wants 'pi' sign if they can't simply install on i. e. Android QPython environment Please declare encoding in module or remove 'pi' sign.

**Comment by jashandeep-sohi** [comment]
Fixed in https://github.com/jashandeep-sohi/python-blowfish/pull/19
