### ISSUE TITLE
there's warning in dist.py

### ISSUE THREAD

**Issue by ikhda-has** [jashandeep-sohi/python-blowfish#24]
Import "Cython.Compiler.Main" could not be resolved

**Comment by jashandeep-sohi** [comment]
Need more context. When are you seeing this message? It would also help if you could post the entire output.

**Comment by ikhda-has** [comment]
already solve the problem by installing Cython. but still cannot see the
result. Is there any packages that should be installed again?
i'm sorry, i don't have any clue toward the codes, i'm new using blowfish.
need help

Pada tanggal Sel, 7 Des 2021 13.45, Jashandeep Sohi <
***@***.***> menulis:

**Comment by jashandeep-sohi** [comment]
I'm not sure I understand. What's the result you're looking for?

**Comment by ikhda-has** [comment]
What is the actual result of this codes? maybe that is the one that i want,
cause I cannot see the result or any hint

Pada tanggal Min, 12 Des 2021 03.31, Jashandeep Sohi <
***@***.***> menulis:

**Comment by jashandeep-sohi** [comment]
So this is a library for the Blowfish cipher in Python. Once you've installed it, you can follow along the usage guide https://github.com/jashandeep-sohi/python-blowfish#usage

**Comment by ikhda-has** [comment]
Thank you, I'll check it out and try to understand it more

Pada tanggal Min, 12 Des 2021 07.32, Jashandeep Sohi <
***@***.***> menulis:
