### ISSUE TITLE
SyntaxError: Non-ASCII character '\xcf' in file blowfish.py on line 32

### ISSUE THREAD

**Issue by freezlite** [jashandeep-sohi/python-blowfish#8]
Put chebang coding or something, cant install from pip

**Comment by jashandeep-sohi** [comment]
Thanks for the heads up.
It's a problem with the unicode pi symbol ``π``.
But it's working on my system (Linux, Python 3.4).

What system are you trying to install it on, if you don't mind me asking?

**Comment by freezlite** [comment]
I'm using 2.7 python, i know that in 3.4 it's pretty well, but such error ...

**Comment by jashandeep-sohi** [comment]
Ahh okay... I wrote the module to be compatiable w/ only Python 3.4.
It relies on a few function only found in the Python 3.4 distribution (i.e. ``struct.iter_unpack``), so you can't run it in python 2.7.

Closing this issue.
